// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef PublicKey AccountID;

//  ===========================================================================

case class AccountID (self: PublicKey) {
  def encode(stream: XdrDataOutputStream): Unit = {
    self.encode(stream)
  }
}
object AccountID {
  def decode(stream: XdrDataInputStream): AccountID = AccountID(PublicKey.decode(stream))
}
