// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum AccountMergeResultCode
//  {
//      // codes considered as "success" for the operation
//      ACCOUNT_MERGE_SUCCESS = 0,
//      // codes considered as "failure" for the operation
//      ACCOUNT_MERGE_MALFORMED = -1,       // can't merge onto itself
//      ACCOUNT_MERGE_NO_ACCOUNT = -2,      // destination does not exist
//      ACCOUNT_MERGE_IMMUTABLE_SET = -3,   // source account has AUTH_IMMUTABLE set
//      ACCOUNT_MERGE_HAS_SUB_ENTRIES = -4, // account has trust lines/offers
//      ACCOUNT_MERGE_SEQNUM_TOO_FAR = -5   // sequence number is over max allowed
//  };

//  ===========================================================================

sealed class AccountMergeResultCode (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object AccountMergeResultCode {
  def decode(stream: XdrDataInputStream): AccountMergeResultCode = stream.readInt() match {
    case 0 => ACCOUNT_MERGE_SUCCESS
    case -1 => ACCOUNT_MERGE_MALFORMED
    case -2 => ACCOUNT_MERGE_NO_ACCOUNT
    case -3 => ACCOUNT_MERGE_IMMUTABLE_SET
    case -4 => ACCOUNT_MERGE_HAS_SUB_ENTRIES
    case -5 => ACCOUNT_MERGE_SEQNUM_TOO_FAR
    case i => throw new IllegalArgumentException(s"AccountMergeResultCode value $i is invalid")
  }

  case object ACCOUNT_MERGE_SUCCESS extends AccountMergeResultCode(0)
  case object ACCOUNT_MERGE_MALFORMED extends AccountMergeResultCode(-1)
  case object ACCOUNT_MERGE_NO_ACCOUNT extends AccountMergeResultCode(-2)
  case object ACCOUNT_MERGE_IMMUTABLE_SET extends AccountMergeResultCode(-3)
  case object ACCOUNT_MERGE_HAS_SUB_ENTRIES extends AccountMergeResultCode(-4)
  case object ACCOUNT_MERGE_SEQNUM_TOO_FAR extends AccountMergeResultCode(-5)
}
