// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  union AllowTrustResult switch (AllowTrustResultCode code)
//  {
//  case ALLOW_TRUST_SUCCESS:
//      void;
//  default:
//      void;
//  };

//  ===========================================================================

sealed trait AllowTrustResult {
  def encode(stream: XdrDataOutputStream): Unit
}

object AllowTrustResult {
  def decode(stream: XdrDataInputStream): AllowTrustResult = AllowTrustResultCode.decode(stream) match {
    case AllowTrustResultCode.ALLOW_TRUST_SUCCESS => ALLOW_TRUST_SUCCESS
    case d => Default(d)
  }

  case object ALLOW_TRUST_SUCCESS extends AllowTrustResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      AllowTrustResultCode.ALLOW_TRUST_SUCCESS.encode(stream)
    }
  }
  case class Default(d: AllowTrustResultCode) extends AllowTrustResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      d.encode(stream)
    }
  }
}
