// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum AssetType
//  {
//      ASSET_TYPE_NATIVE = 0,
//      ASSET_TYPE_CREDIT_ALPHANUM4 = 1,
//      ASSET_TYPE_CREDIT_ALPHANUM12 = 2
//  };

//  ===========================================================================

sealed class AssetType (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object AssetType {
  def decode(stream: XdrDataInputStream): AssetType = stream.readInt() match {
    case 0 => ASSET_TYPE_NATIVE
    case 1 => ASSET_TYPE_CREDIT_ALPHANUM4
    case 2 => ASSET_TYPE_CREDIT_ALPHANUM12
    case i => throw new IllegalArgumentException(s"AssetType value $i is invalid")
  }

  case object ASSET_TYPE_NATIVE extends AssetType(0)
  case object ASSET_TYPE_CREDIT_ALPHANUM4 extends AssetType(1)
  case object ASSET_TYPE_CREDIT_ALPHANUM12 extends AssetType(2)
}
