// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct Auth
//  {
//      // Empty message, just to confirm
//      // establishment of MAC keys.
//      int unused;
//  };

//  ===========================================================================

case class Auth (
  unused: Int
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeInt(unused)
  }
}

object Auth {
  def decode(stream: XdrDataInputStream): Auth = Auth(
    stream.readInt
  )
}
