// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct AuthCert
//  {
//      Curve25519Public pubkey;
//      uint64 expiration;
//      Signature sig;
//  };

//  ===========================================================================

case class AuthCert (
  pubkey: Curve25519Public, 
  expiration: Uint64, 
  sig: Signature
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    pubkey.encode(stream)
    expiration.encode(stream)
    sig.encode(stream)
  }
}

object AuthCert {
  def decode(stream: XdrDataInputStream): AuthCert = AuthCert(
    Curve25519Public.decode(stream),
    Uint64.decode(stream),
    Signature.decode(stream)
  )
}
