// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum BucketEntryType
//  {
//      LIVEENTRY = 0,
//      DEADENTRY = 1
//  };

//  ===========================================================================

sealed class BucketEntryType (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object BucketEntryType {
  def decode(stream: XdrDataInputStream): BucketEntryType = stream.readInt() match {
    case 0 => LIVEENTRY
    case 1 => DEADENTRY
    case i => throw new IllegalArgumentException(s"BucketEntryType value $i is invalid")
  }

  case object LIVEENTRY extends BucketEntryType(0)
  case object DEADENTRY extends BucketEntryType(1)
}
