// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  union BumpSequenceResult switch (BumpSequenceResultCode code)
//  {
//  case BUMP_SEQUENCE_SUCCESS:
//      void;
//  default:
//      void;
//  };

//  ===========================================================================

sealed trait BumpSequenceResult {
  def encode(stream: XdrDataOutputStream): Unit
}

object BumpSequenceResult {
  def decode(stream: XdrDataInputStream): BumpSequenceResult = BumpSequenceResultCode.decode(stream) match {
    case BumpSequenceResultCode.BUMP_SEQUENCE_SUCCESS => BUMP_SEQUENCE_SUCCESS
    case d => Default(d)
  }

  case object BUMP_SEQUENCE_SUCCESS extends BumpSequenceResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      BumpSequenceResultCode.BUMP_SEQUENCE_SUCCESS.encode(stream)
    }
  }
  case class Default(d: BumpSequenceResultCode) extends BumpSequenceResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      d.encode(stream)
    }
  }
}
