// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum BumpSequenceResultCode
//  {
//      // codes considered as "success" for the operation
//      BUMP_SEQUENCE_SUCCESS = 0,
//      // codes considered as "failure" for the operation
//      BUMP_SEQUENCE_BAD_SEQ = -1 // `bumpTo` is not within bounds
//  };

//  ===========================================================================

sealed class BumpSequenceResultCode (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object BumpSequenceResultCode {
  def decode(stream: XdrDataInputStream): BumpSequenceResultCode = stream.readInt() match {
    case 0 => BUMP_SEQUENCE_SUCCESS
    case -1 => BUMP_SEQUENCE_BAD_SEQ
    case i => throw new IllegalArgumentException(s"BumpSequenceResultCode value $i is invalid")
  }

  case object BUMP_SEQUENCE_SUCCESS extends BumpSequenceResultCode(0)
  case object BUMP_SEQUENCE_BAD_SEQ extends BumpSequenceResultCode(-1)
}
