// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct BumpSequenceOp
//  {
//      SequenceNumber bumpTo;
//  };

//  ===========================================================================

case class BumpSequenceOp (
  bumpTo: SequenceNumber
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    bumpTo.encode(stream)
  }
}

object BumpSequenceOp {
  def decode(stream: XdrDataInputStream): BumpSequenceOp = BumpSequenceOp(
    SequenceNumber.decode(stream)
  )
}
