// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct ChangeTrustOp
//  {
//      Asset line;
//  
//      // if limit is set to 0, deletes the trust line
//      int64 limit;
//  };

//  ===========================================================================

case class ChangeTrustOp (
  line: Asset, 
  limit: Int64
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    line.encode(stream)
    limit.encode(stream)
  }
}

object ChangeTrustOp {
  def decode(stream: XdrDataInputStream): ChangeTrustOp = ChangeTrustOp(
    Asset.decode(stream),
    Int64.decode(stream)
  )
}
