// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct ClaimOfferAtom
//  {
//      // emitted to identify the offer
//      AccountID sellerID; // Account that owns the offer
//      uint64 offerID;
//  
//      // amount and asset taken from the owner
//      Asset assetSold;
//      int64 amountSold;
//  
//      // amount and asset sent to the owner
//      Asset assetBought;
//      int64 amountBought;
//  };

//  ===========================================================================

case class ClaimOfferAtom (
  sellerID: AccountID, 
  offerID: Uint64, 
  assetSold: Asset, 
  amountSold: Int64, 
  assetBought: Asset, 
  amountBought: Int64
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    sellerID.encode(stream)
    offerID.encode(stream)
    assetSold.encode(stream)
    amountSold.encode(stream)
    assetBought.encode(stream)
    amountBought.encode(stream)
  }
}

object ClaimOfferAtom {
  def decode(stream: XdrDataInputStream): ClaimOfferAtom = ClaimOfferAtom(
    AccountID.decode(stream),
    Uint64.decode(stream),
    Asset.decode(stream),
    Int64.decode(stream),
    Asset.decode(stream),
    Int64.decode(stream)
  )
}
