// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum CreateAccountResultCode
//  {
//      // codes considered as "success" for the operation
//      CREATE_ACCOUNT_SUCCESS = 0, // account was created
//  
//      // codes considered as "failure" for the operation
//      CREATE_ACCOUNT_MALFORMED = -1,   // invalid destination
//      CREATE_ACCOUNT_UNDERFUNDED = -2, // not enough funds in source account
//      CREATE_ACCOUNT_LOW_RESERVE =
//          -3, // would create an account below the min reserve
//      CREATE_ACCOUNT_ALREADY_EXIST = -4 // account already exists
//  };

//  ===========================================================================

sealed class CreateAccountResultCode (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object CreateAccountResultCode {
  def decode(stream: XdrDataInputStream): CreateAccountResultCode = stream.readInt() match {
    case 0 => CREATE_ACCOUNT_SUCCESS
    case -1 => CREATE_ACCOUNT_MALFORMED
    case -2 => CREATE_ACCOUNT_UNDERFUNDED
    case -3 => CREATE_ACCOUNT_LOW_RESERVE
    case -4 => CREATE_ACCOUNT_ALREADY_EXIST
    case i => throw new IllegalArgumentException(s"CreateAccountResultCode value $i is invalid")
  }

  case object CREATE_ACCOUNT_SUCCESS extends CreateAccountResultCode(0)
  case object CREATE_ACCOUNT_MALFORMED extends CreateAccountResultCode(-1)
  case object CREATE_ACCOUNT_UNDERFUNDED extends CreateAccountResultCode(-2)
  case object CREATE_ACCOUNT_LOW_RESERVE extends CreateAccountResultCode(-3)
  case object CREATE_ACCOUNT_ALREADY_EXIST extends CreateAccountResultCode(-4)
}
