// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct CreatePassiveOfferOp
//  {
//      Asset selling; // A
//      Asset buying;  // B
//      int64 amount;  // amount taker gets. if set to 0, delete the offer
//      Price price;   // cost of A in terms of B
//  };

//  ===========================================================================

case class CreatePassiveOfferOp (
  selling: Asset, 
  buying: Asset, 
  amount: Int64, 
  price: Price
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    selling.encode(stream)
    buying.encode(stream)
    amount.encode(stream)
    price.encode(stream)
  }
}

object CreatePassiveOfferOp {
  def decode(stream: XdrDataInputStream): CreatePassiveOfferOp = CreatePassiveOfferOp(
    Asset.decode(stream),
    Asset.decode(stream),
    Int64.decode(stream),
    Price.decode(stream)
  )
}
