// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct CreateAccountOp
//  {
//      AccountID destination; // account to create
//      int64 startingBalance; // amount they end up with
//  };

//  ===========================================================================

case class CreateAccountOp (
  destination: AccountID, 
  startingBalance: Int64
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    destination.encode(stream)
    startingBalance.encode(stream)
  }
}

object CreateAccountOp {
  def decode(stream: XdrDataInputStream): CreateAccountOp = CreateAccountOp(
    AccountID.decode(stream),
    Int64.decode(stream)
  )
}
