// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  union CreateAccountResult switch (CreateAccountResultCode code)
//  {
//  case CREATE_ACCOUNT_SUCCESS:
//      void;
//  default:
//      void;
//  };

//  ===========================================================================

sealed trait CreateAccountResult {
  def encode(stream: XdrDataOutputStream): Unit
}

object CreateAccountResult {
  def decode(stream: XdrDataInputStream): CreateAccountResult = CreateAccountResultCode.decode(stream) match {
    case CreateAccountResultCode.CREATE_ACCOUNT_SUCCESS => CREATE_ACCOUNT_SUCCESS
    case d => Default(d)
  }

  case object CREATE_ACCOUNT_SUCCESS extends CreateAccountResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      CreateAccountResultCode.CREATE_ACCOUNT_SUCCESS.encode(stream)
    }
  }
  case class Default(d: CreateAccountResultCode) extends CreateAccountResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      d.encode(stream)
    }
  }
}
