// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct Curve25519Secret
//  {
//          opaque key[32];
//  };

//  ===========================================================================

case class Curve25519Secret (
  key: Array[Byte]
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.write(key, 0, key.length)
  }
}

object Curve25519Secret {
  def decode(stream: XdrDataInputStream): Curve25519Secret = Curve25519Secret(
    stream.readBytes(32)
  )
}
