// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef opaque DataValue<64>;

//  ===========================================================================

case class DataValue (self: Array[Byte]) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeInt(self.length)
    stream.write(self, 0, self.length)
  }
}
object DataValue {
  def decode(stream: XdrDataInputStream): DataValue = DataValue(stream.readBytes(stream.readInt))
}
