// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct DataEntry
//  {
//      AccountID accountID; // account this data belongs to
//      string64 dataName;
//      DataValue dataValue;
//  
//      // reserved for future use
//      union switch (int v)
//      {
//      case 0:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================

case class DataEntry (
  accountID: AccountID, 
  dataName: String64, 
  dataValue: DataValue, 
  ext: DataEntry.Ext
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    accountID.encode(stream)
    dataName.encode(stream)
    dataValue.encode(stream)
    ext.encode(stream)
  }
}

object DataEntry {
  def decode(stream: XdrDataInputStream): DataEntry = DataEntry(
    AccountID.decode(stream),
    String64.decode(stream),
    DataValue.decode(stream),
    Ext.decode(stream)
  )

  sealed trait Ext {
    def encode(stream: XdrDataOutputStream): Unit
  }

  object Ext {
    def decode(stream: XdrDataInputStream): Ext = stream.readInt match {
      case 0 => R_0
      case d => throw new IllegalArgumentException(s"Int value $d is invalid")
    }

    case object R_0 extends Ext {
      def encode(stream: XdrDataOutputStream): Unit = {
        stream.writeInt(0)
      }
    }
  }
}
