// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct DontHave
//  {
//      MessageType type;
//      uint256 reqHash;
//  };

//  ===========================================================================

case class DontHave (
  `type`: MessageType, 
  reqHash: Uint256
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    `type`.encode(stream)
    reqHash.encode(stream)
  }
}

object DontHave {
  def decode(stream: XdrDataInputStream): DontHave = DontHave(
    MessageType.decode(stream),
    Uint256.decode(stream)
  )
}
