// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct Error
//  {
//      ErrorCode code;
//      string msg<100>;
//  };

//  ===========================================================================

case class Error (
  code: ErrorCode, 
  msg: String
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    code.encode(stream)
    stream.writeString(msg)
  }
}

object Error {
  def decode(stream: XdrDataInputStream): Error = Error(
    ErrorCode.decode(stream),
    stream.readString
  )
}
