// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct HmacSha256Mac
//  {
//          opaque mac[32];
//  };

//  ===========================================================================

case class HmacSha256Mac (
  mac: Array[Byte]
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.write(mac, 0, mac.length)
  }
}

object HmacSha256Mac {
  def decode(stream: XdrDataInputStream): HmacSha256Mac = HmacSha256Mac(
    stream.readBytes(32)
  )
}
