// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct HmacSha256Key
//  {
//          opaque key[32];
//  };

//  ===========================================================================

case class HmacSha256Key (
  key: Array[Byte]
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.write(key, 0, key.length)
  }
}

object HmacSha256Key {
  def decode(stream: XdrDataInputStream): HmacSha256Key = HmacSha256Key(
    stream.readBytes(32)
  )
}
