// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  union InflationResult switch (InflationResultCode code)
//  {
//  case INFLATION_SUCCESS:
//      InflationPayout payouts<>;
//  default:
//      void;
//  };

//  ===========================================================================

sealed trait InflationResult {
  def encode(stream: XdrDataOutputStream): Unit
}

object InflationResult {
  def decode(stream: XdrDataInputStream): InflationResult = InflationResultCode.decode(stream) match {
    case InflationResultCode.INFLATION_SUCCESS => INFLATION_SUCCESS((0 until stream.readInt).map(_ => InflationPayout.decode(stream)).toArray)
    case d => Default(d)
  }

  case class INFLATION_SUCCESS(x: Array[InflationPayout]) extends InflationResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      InflationResultCode.INFLATION_SUCCESS.encode(stream)
      stream.writeInt(x.length)
      x.foreach { _.encode(stream) }
    }
  }
  case class Default(d: InflationResultCode) extends InflationResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      d.encode(stream)
    }
  }
}
