// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum InflationResultCode
//  {
//      // codes considered as "success" for the operation
//      INFLATION_SUCCESS = 0,
//      // codes considered as "failure" for the operation
//      INFLATION_NOT_TIME = -1
//  };

//  ===========================================================================

sealed class InflationResultCode (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object InflationResultCode {
  def decode(stream: XdrDataInputStream): InflationResultCode = stream.readInt() match {
    case 0 => INFLATION_SUCCESS
    case -1 => INFLATION_NOT_TIME
    case i => throw new IllegalArgumentException(s"InflationResultCode value $i is invalid")
  }

  case object INFLATION_SUCCESS extends InflationResultCode(0)
  case object INFLATION_NOT_TIME extends InflationResultCode(-1)
}
