// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef int int32;

//  ===========================================================================

case class Int32 (self: Int) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeInt(self)
  }
}
object Int32 {
  def decode(stream: XdrDataInputStream): Int32 = Int32(stream.readInt)
}
