// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef hyper int64;

//  ===========================================================================

case class Int64 (self: Long) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeLong(self)
  }
}
object Int64 {
  def decode(stream: XdrDataInputStream): Int64 = Int64(stream.readLong)
}
