// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum LedgerEntryChangeType
//  {
//      LEDGER_ENTRY_CREATED = 0, // entry was added to the ledger
//      LEDGER_ENTRY_UPDATED = 1, // entry was modified in the ledger
//      LEDGER_ENTRY_REMOVED = 2, // entry was removed from the ledger
//      LEDGER_ENTRY_STATE = 3    // value of the entry
//  };

//  ===========================================================================

sealed class LedgerEntryChangeType (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object LedgerEntryChangeType {
  def decode(stream: XdrDataInputStream): LedgerEntryChangeType = stream.readInt() match {
    case 0 => LEDGER_ENTRY_CREATED
    case 1 => LEDGER_ENTRY_UPDATED
    case 2 => LEDGER_ENTRY_REMOVED
    case 3 => LEDGER_ENTRY_STATE
    case i => throw new IllegalArgumentException(s"LedgerEntryChangeType value $i is invalid")
  }

  case object LEDGER_ENTRY_CREATED extends LedgerEntryChangeType(0)
  case object LEDGER_ENTRY_UPDATED extends LedgerEntryChangeType(1)
  case object LEDGER_ENTRY_REMOVED extends LedgerEntryChangeType(2)
  case object LEDGER_ENTRY_STATE extends LedgerEntryChangeType(3)
}
