// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef LedgerEntryChange LedgerEntryChanges<>;

//  ===========================================================================

case class LedgerEntryChanges (self: Array[LedgerEntryChange]) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeInt(self.length)
    self.foreach { _.encode(stream) }
  }
}
object LedgerEntryChanges {
  def decode(stream: XdrDataInputStream): LedgerEntryChanges = LedgerEntryChanges((0 until stream.readInt).map(_ => LedgerEntryChange.decode(stream)).toArray)
}
