// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum ManageOfferEffect
//  {
//      MANAGE_OFFER_CREATED = 0,
//      MANAGE_OFFER_UPDATED = 1,
//      MANAGE_OFFER_DELETED = 2
//  };

//  ===========================================================================

sealed class ManageOfferEffect (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object ManageOfferEffect {
  def decode(stream: XdrDataInputStream): ManageOfferEffect = stream.readInt() match {
    case 0 => MANAGE_OFFER_CREATED
    case 1 => MANAGE_OFFER_UPDATED
    case 2 => MANAGE_OFFER_DELETED
    case i => throw new IllegalArgumentException(s"ManageOfferEffect value $i is invalid")
  }

  case object MANAGE_OFFER_CREATED extends ManageOfferEffect(0)
  case object MANAGE_OFFER_UPDATED extends ManageOfferEffect(1)
  case object MANAGE_OFFER_DELETED extends ManageOfferEffect(2)
}
