// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct ManageOfferOp
//  {
//      Asset selling;
//      Asset buying;
//      int64 amount; // amount being sold. if set to 0, delete the offer
//      Price price;  // price of thing being sold in terms of what you are buying
//  
//      // 0=create a new offer, otherwise edit an existing offer
//      uint64 offerID;
//  };

//  ===========================================================================

case class ManageOfferOp (
  selling: Asset, 
  buying: Asset, 
  amount: Int64, 
  price: Price, 
  offerID: Uint64
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    selling.encode(stream)
    buying.encode(stream)
    amount.encode(stream)
    price.encode(stream)
    offerID.encode(stream)
  }
}

object ManageOfferOp {
  def decode(stream: XdrDataInputStream): ManageOfferOp = ManageOfferOp(
    Asset.decode(stream),
    Asset.decode(stream),
    Int64.decode(stream),
    Price.decode(stream),
    Uint64.decode(stream)
  )
}
