// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  union ManageOfferResult switch (ManageOfferResultCode code)
//  {
//  case MANAGE_OFFER_SUCCESS:
//      ManageOfferSuccessResult success;
//  default:
//      void;
//  };

//  ===========================================================================

sealed trait ManageOfferResult {
  def encode(stream: XdrDataOutputStream): Unit
}

object ManageOfferResult {
  def decode(stream: XdrDataInputStream): ManageOfferResult = ManageOfferResultCode.decode(stream) match {
    case ManageOfferResultCode.MANAGE_OFFER_SUCCESS => MANAGE_OFFER_SUCCESS(ManageOfferSuccessResult.decode(stream))
    case d => Default(d)
  }

  case class MANAGE_OFFER_SUCCESS(x: ManageOfferSuccessResult) extends ManageOfferResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      ManageOfferResultCode.MANAGE_OFFER_SUCCESS.encode(stream)
      x.encode(stream)
    }
  }
  case class Default(d: ManageOfferResultCode) extends ManageOfferResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      d.encode(stream)
    }
  }
}
