// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum ManageOfferResultCode
//  {
//      // codes considered as "success" for the operation
//      MANAGE_OFFER_SUCCESS = 0,
//  
//      // codes considered as "failure" for the operation
//      MANAGE_OFFER_MALFORMED = -1,     // generated offer would be invalid
//      MANAGE_OFFER_SELL_NO_TRUST = -2, // no trust line for what we're selling
//      MANAGE_OFFER_BUY_NO_TRUST = -3,  // no trust line for what we're buying
//      MANAGE_OFFER_SELL_NOT_AUTHORIZED = -4, // not authorized to sell
//      MANAGE_OFFER_BUY_NOT_AUTHORIZED = -5,  // not authorized to buy
//      MANAGE_OFFER_LINE_FULL = -6,      // can't receive more of what it's buying
//      MANAGE_OFFER_UNDERFUNDED = -7,    // doesn't hold what it's trying to sell
//      MANAGE_OFFER_CROSS_SELF = -8,     // would cross an offer from the same user
//      MANAGE_OFFER_SELL_NO_ISSUER = -9, // no issuer for what we're selling
//      MANAGE_OFFER_BUY_NO_ISSUER = -10, // no issuer for what we're buying
//  
//      // update errors
//      MANAGE_OFFER_NOT_FOUND = -11, // offerID does not match an existing offer
//  
//      MANAGE_OFFER_LOW_RESERVE = -12 // not enough funds to create a new Offer
//  };

//  ===========================================================================

sealed class ManageOfferResultCode (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object ManageOfferResultCode {
  def decode(stream: XdrDataInputStream): ManageOfferResultCode = stream.readInt() match {
    case 0 => MANAGE_OFFER_SUCCESS
    case -1 => MANAGE_OFFER_MALFORMED
    case -2 => MANAGE_OFFER_SELL_NO_TRUST
    case -3 => MANAGE_OFFER_BUY_NO_TRUST
    case -4 => MANAGE_OFFER_SELL_NOT_AUTHORIZED
    case -5 => MANAGE_OFFER_BUY_NOT_AUTHORIZED
    case -6 => MANAGE_OFFER_LINE_FULL
    case -7 => MANAGE_OFFER_UNDERFUNDED
    case -8 => MANAGE_OFFER_CROSS_SELF
    case -9 => MANAGE_OFFER_SELL_NO_ISSUER
    case -10 => MANAGE_OFFER_BUY_NO_ISSUER
    case -11 => MANAGE_OFFER_NOT_FOUND
    case -12 => MANAGE_OFFER_LOW_RESERVE
    case i => throw new IllegalArgumentException(s"ManageOfferResultCode value $i is invalid")
  }

  case object MANAGE_OFFER_SUCCESS extends ManageOfferResultCode(0)
  case object MANAGE_OFFER_MALFORMED extends ManageOfferResultCode(-1)
  case object MANAGE_OFFER_SELL_NO_TRUST extends ManageOfferResultCode(-2)
  case object MANAGE_OFFER_BUY_NO_TRUST extends ManageOfferResultCode(-3)
  case object MANAGE_OFFER_SELL_NOT_AUTHORIZED extends ManageOfferResultCode(-4)
  case object MANAGE_OFFER_BUY_NOT_AUTHORIZED extends ManageOfferResultCode(-5)
  case object MANAGE_OFFER_LINE_FULL extends ManageOfferResultCode(-6)
  case object MANAGE_OFFER_UNDERFUNDED extends ManageOfferResultCode(-7)
  case object MANAGE_OFFER_CROSS_SELF extends ManageOfferResultCode(-8)
  case object MANAGE_OFFER_SELL_NO_ISSUER extends ManageOfferResultCode(-9)
  case object MANAGE_OFFER_BUY_NO_ISSUER extends ManageOfferResultCode(-10)
  case object MANAGE_OFFER_NOT_FOUND extends ManageOfferResultCode(-11)
  case object MANAGE_OFFER_LOW_RESERVE extends ManageOfferResultCode(-12)
}
