// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  union ManageDataResult switch (ManageDataResultCode code)
//  {
//  case MANAGE_DATA_SUCCESS:
//      void;
//  default:
//      void;
//  };

//  ===========================================================================

sealed trait ManageDataResult {
  def encode(stream: XdrDataOutputStream): Unit
}

object ManageDataResult {
  def decode(stream: XdrDataInputStream): ManageDataResult = ManageDataResultCode.decode(stream) match {
    case ManageDataResultCode.MANAGE_DATA_SUCCESS => MANAGE_DATA_SUCCESS
    case d => Default(d)
  }

  case object MANAGE_DATA_SUCCESS extends ManageDataResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      ManageDataResultCode.MANAGE_DATA_SUCCESS.encode(stream)
    }
  }
  case class Default(d: ManageDataResultCode) extends ManageDataResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      d.encode(stream)
    }
  }
}
