// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum MemoType
//  {
//      MEMO_NONE = 0,
//      MEMO_TEXT = 1,
//      MEMO_ID = 2,
//      MEMO_HASH = 3,
//      MEMO_RETURN = 4
//  };

//  ===========================================================================

sealed class MemoType (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object MemoType {
  def decode(stream: XdrDataInputStream): MemoType = stream.readInt() match {
    case 0 => MEMO_NONE
    case 1 => MEMO_TEXT
    case 2 => MEMO_ID
    case 3 => MEMO_HASH
    case 4 => MEMO_RETURN
    case i => throw new IllegalArgumentException(s"MemoType value $i is invalid")
  }

  case object MEMO_NONE extends MemoType(0)
  case object MEMO_TEXT extends MemoType(1)
  case object MEMO_ID extends MemoType(2)
  case object MEMO_HASH extends MemoType(3)
  case object MEMO_RETURN extends MemoType(4)
}
