// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum OfferEntryFlags
//  {
//      // issuer has authorized account to perform transactions with its credit
//      PASSIVE_FLAG = 1
//  };

//  ===========================================================================

sealed class OfferEntryFlags (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object OfferEntryFlags {
  def decode(stream: XdrDataInputStream): OfferEntryFlags = stream.readInt() match {
    case 1 => PASSIVE_FLAG
    case i => throw new IllegalArgumentException(s"OfferEntryFlags value $i is invalid")
  }

  case object PASSIVE_FLAG extends OfferEntryFlags(1)
}
