// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct OperationMeta
//  {
//      LedgerEntryChanges changes;
//  };

//  ===========================================================================

case class OperationMeta (
  changes: LedgerEntryChanges
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    changes.encode(stream)
  }
}

object OperationMeta {
  def decode(stream: XdrDataInputStream): OperationMeta = OperationMeta(
    LedgerEntryChanges.decode(stream)
  )
}
