// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct PaymentOp
//  {
//      AccountID destination; // recipient of the payment
//      Asset asset;           // what they end up with
//      int64 amount;          // amount they end up with
//  };

//  ===========================================================================

case class PaymentOp (
  destination: AccountID, 
  asset: Asset, 
  amount: Int64
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    destination.encode(stream)
    asset.encode(stream)
    amount.encode(stream)
  }
}

object PaymentOp {
  def decode(stream: XdrDataInputStream): PaymentOp = PaymentOp(
    AccountID.decode(stream),
    Asset.decode(stream),
    Int64.decode(stream)
  )
}
