// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum PublicKeyType
//  {
//      PUBLIC_KEY_TYPE_ED25519 = KEY_TYPE_ED25519
//  };

//  ===========================================================================

sealed class PublicKeyType (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object PublicKeyType {
  def decode(stream: XdrDataInputStream): PublicKeyType = stream.readInt() match {
    case 0 => PUBLIC_KEY_TYPE_ED25519
    case i => throw new IllegalArgumentException(s"PublicKeyType value $i is invalid")
  }

  case object PUBLIC_KEY_TYPE_ED25519 extends PublicKeyType(0)
}
