// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  union PublicKey switch (PublicKeyType type)
//  {
//  case PUBLIC_KEY_TYPE_ED25519:
//      uint256 ed25519;
//  };

//  ===========================================================================

sealed trait PublicKey {
  def encode(stream: XdrDataOutputStream): Unit
}

object PublicKey {
  def decode(stream: XdrDataInputStream): PublicKey = PublicKeyType.decode(stream) match {
    case PublicKeyType.PUBLIC_KEY_TYPE_ED25519 => PUBLIC_KEY_TYPE_ED25519(Uint256.decode(stream))
    case d => throw new IllegalArgumentException(s"PublicKeyType value $d is invalid")
  }

  case class PUBLIC_KEY_TYPE_ED25519(x: Uint256) extends PublicKey {
    def encode(stream: XdrDataOutputStream): Unit = {
      PublicKeyType.PUBLIC_KEY_TYPE_ED25519.encode(stream)
      x.encode(stream)
    }
  }
}
