// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct SCPBallot
//  {
//      uint32 counter; // n
//      Value value;    // x
//  };

//  ===========================================================================

case class SCPBallot (
  counter: Uint32, 
  value: Value
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    counter.encode(stream)
    value.encode(stream)
  }
}

object SCPBallot {
  def decode(stream: XdrDataInputStream): SCPBallot = SCPBallot(
    Uint32.decode(stream),
    Value.decode(stream)
  )
}
