// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct SCPEnvelope
//  {
//      SCPStatement statement;
//      Signature signature;
//  };

//  ===========================================================================

case class SCPEnvelope (
  statement: SCPStatement, 
  signature: Signature
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    statement.encode(stream)
    signature.encode(stream)
  }
}

object SCPEnvelope {
  def decode(stream: XdrDataInputStream): SCPEnvelope = SCPEnvelope(
    SCPStatement.decode(stream),
    Signature.decode(stream)
  )
}
