// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct SCPHistoryEntryV0
//  {
//      SCPQuorumSet quorumSets<>; // additional quorum sets used by ledgerMessages
//      LedgerSCPMessages ledgerMessages;
//  };

//  ===========================================================================

case class SCPHistoryEntryV0 (
  quorumSets: Array[SCPQuorumSet], 
  ledgerMessages: LedgerSCPMessages
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeInt(quorumSets.length)
    quorumSets.foreach { _.encode(stream) }
    ledgerMessages.encode(stream)
  }
}

object SCPHistoryEntryV0 {
  def decode(stream: XdrDataInputStream): SCPHistoryEntryV0 = SCPHistoryEntryV0(
    (0 until stream.readInt).map(_ => SCPQuorumSet.decode(stream)).toArray,
    LedgerSCPMessages.decode(stream)
  )
}
