// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct SCPNomination
//  {
//      Hash quorumSetHash; // D
//      Value votes<>;      // X
//      Value accepted<>;   // Y
//  };

//  ===========================================================================

case class SCPNomination (
  quorumSetHash: Hash, 
  votes: Array[Value], 
  accepted: Array[Value]
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    quorumSetHash.encode(stream)
    stream.writeInt(votes.length)
    votes.foreach { _.encode(stream) }
    stream.writeInt(accepted.length)
    accepted.foreach { _.encode(stream) }
  }
}

object SCPNomination {
  def decode(stream: XdrDataInputStream): SCPNomination = SCPNomination(
    Hash.decode(stream),
    (0 until stream.readInt).map(_ => Value.decode(stream)).toArray,
    (0 until stream.readInt).map(_ => Value.decode(stream)).toArray
  )
}
