// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct SCPQuorumSet
//  {
//      uint32 threshold;
//      PublicKey validators<>;
//      SCPQuorumSet innerSets<>;
//  };

//  ===========================================================================

case class SCPQuorumSet (
  threshold: Uint32, 
  validators: Array[PublicKey], 
  innerSets: Array[SCPQuorumSet]
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    threshold.encode(stream)
    stream.writeInt(validators.length)
    validators.foreach { _.encode(stream) }
    stream.writeInt(innerSets.length)
    innerSets.foreach { _.encode(stream) }
  }
}

object SCPQuorumSet {
  def decode(stream: XdrDataInputStream): SCPQuorumSet = SCPQuorumSet(
    Uint32.decode(stream),
    (0 until stream.readInt).map(_ => PublicKey.decode(stream)).toArray,
    (0 until stream.readInt).map(_ => SCPQuorumSet.decode(stream)).toArray
  )
}
