// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef int64 SequenceNumber;

//  ===========================================================================

case class SequenceNumber (self: Int64) {
  def encode(stream: XdrDataOutputStream): Unit = {
    self.encode(stream)
  }
}
object SequenceNumber {
  def decode(stream: XdrDataInputStream): SequenceNumber = SequenceNumber(Int64.decode(stream))
}
