// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  union SetOptionsResult switch (SetOptionsResultCode code)
//  {
//  case SET_OPTIONS_SUCCESS:
//      void;
//  default:
//      void;
//  };

//  ===========================================================================

sealed trait SetOptionsResult {
  def encode(stream: XdrDataOutputStream): Unit
}

object SetOptionsResult {
  def decode(stream: XdrDataInputStream): SetOptionsResult = SetOptionsResultCode.decode(stream) match {
    case SetOptionsResultCode.SET_OPTIONS_SUCCESS => SET_OPTIONS_SUCCESS
    case d => Default(d)
  }

  case object SET_OPTIONS_SUCCESS extends SetOptionsResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      SetOptionsResultCode.SET_OPTIONS_SUCCESS.encode(stream)
    }
  }
  case class Default(d: SetOptionsResultCode) extends SetOptionsResult {
    def encode(stream: XdrDataOutputStream): Unit = {
      d.encode(stream)
    }
  }
}
