// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef opaque Signature<64>;

//  ===========================================================================

case class Signature (self: Array[Byte]) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeInt(self.length)
    stream.write(self, 0, self.length)
  }
}
object Signature {
  def decode(stream: XdrDataInputStream): Signature = Signature(stream.readBytes(stream.readInt))
}
