// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef opaque SignatureHint[4];

//  ===========================================================================

case class SignatureHint (self: Array[Byte]) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.write(self, 0, self.length)
  }
}
object SignatureHint {
  def decode(stream: XdrDataInputStream): SignatureHint = SignatureHint(stream.readBytes(4))
}
