// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct Signer
//  {
//      SignerKey key;
//      uint32 weight; // really only need 1byte
//  };

//  ===========================================================================

case class Signer (
  key: SignerKey, 
  weight: Uint32
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    key.encode(stream)
    weight.encode(stream)
  }
}

object Signer {
  def decode(stream: XdrDataInputStream): Signer = Signer(
    SignerKey.decode(stream),
    Uint32.decode(stream)
  )
}
