// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct SimplePaymentResult
//  {
//      AccountID destination;
//      Asset asset;
//      int64 amount;
//  };

//  ===========================================================================

case class SimplePaymentResult (
  destination: AccountID, 
  asset: Asset, 
  amount: Int64
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    destination.encode(stream)
    asset.encode(stream)
    amount.encode(stream)
  }
}

object SimplePaymentResult {
  def decode(stream: XdrDataInputStream): SimplePaymentResult = SimplePaymentResult(
    AccountID.decode(stream),
    Asset.decode(stream),
    Int64.decode(stream)
  )
}
