// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef string string32<32>;

//  ===========================================================================

case class String32 (self: String) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeString(self)
  }
}
object String32 {
  def decode(stream: XdrDataInputStream): String32 = String32(stream.readString)
}
