// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef string string64<64>;

//  ===========================================================================

case class String64 (self: String) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeString(self)
  }
}
object String64 {
  def decode(stream: XdrDataInputStream): String64 = String64(stream.readString)
}
