// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum ThresholdIndexes
//  {
//      THRESHOLD_MASTER_WEIGHT = 0,
//      THRESHOLD_LOW = 1,
//      THRESHOLD_MED = 2,
//      THRESHOLD_HIGH = 3
//  };

//  ===========================================================================

sealed class ThresholdIndexes (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object ThresholdIndexes {
  def decode(stream: XdrDataInputStream): ThresholdIndexes = stream.readInt() match {
    case 0 => THRESHOLD_MASTER_WEIGHT
    case 1 => THRESHOLD_LOW
    case 2 => THRESHOLD_MED
    case 3 => THRESHOLD_HIGH
    case i => throw new IllegalArgumentException(s"ThresholdIndexes value $i is invalid")
  }

  case object THRESHOLD_MASTER_WEIGHT extends ThresholdIndexes(0)
  case object THRESHOLD_LOW extends ThresholdIndexes(1)
  case object THRESHOLD_MED extends ThresholdIndexes(2)
  case object THRESHOLD_HIGH extends ThresholdIndexes(3)
}
