// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef opaque Thresholds[4];

//  ===========================================================================

case class Thresholds (self: Array[Byte]) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.write(self, 0, self.length)
  }
}
object Thresholds {
  def decode(stream: XdrDataInputStream): Thresholds = Thresholds(stream.readBytes(4))
}
