// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct TransactionSet
//  {
//      Hash previousLedgerHash;
//      TransactionEnvelope txs<>;
//  };

//  ===========================================================================

case class TransactionSet (
  previousLedgerHash: Hash, 
  txs: Array[TransactionEnvelope]
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    previousLedgerHash.encode(stream)
    stream.writeInt(txs.length)
    txs.foreach { _.encode(stream) }
  }
}

object TransactionSet {
  def decode(stream: XdrDataInputStream): TransactionSet = TransactionSet(
    Hash.decode(stream),
    (0 until stream.readInt).map(_ => TransactionEnvelope.decode(stream)).toArray
  )
}
