// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct TransactionResultPair
//  {
//      Hash transactionHash;
//      TransactionResult result; // result for the transaction
//  };

//  ===========================================================================

case class TransactionResultPair (
  transactionHash: Hash, 
  result: TransactionResult
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    transactionHash.encode(stream)
    result.encode(stream)
  }
}

object TransactionResultPair {
  def decode(stream: XdrDataInputStream): TransactionResultPair = TransactionResultPair(
    Hash.decode(stream),
    TransactionResult.decode(stream)
  )
}
