// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct TransactionMetaV1
//  {
//      LedgerEntryChanges txChanges; // tx level changes if any
//      OperationMeta operations<>; // meta for each operation
//  };

//  ===========================================================================

case class TransactionMetaV1 (
  txChanges: LedgerEntryChanges, 
  operations: Array[OperationMeta]
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    txChanges.encode(stream)
    stream.writeInt(operations.length)
    operations.foreach { _.encode(stream) }
  }
}

object TransactionMetaV1 {
  def decode(stream: XdrDataInputStream): TransactionMetaV1 = TransactionMetaV1(
    LedgerEntryChanges.decode(stream),
    (0 until stream.readInt).map(_ => OperationMeta.decode(stream)).toArray
  )
}
