// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  struct TransactionHistoryEntry
//  {
//      uint32 ledgerSeq;
//      TransactionSet txSet;
//  
//      // reserved for future use
//      union switch (int v)
//      {
//      case 0:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================

case class TransactionHistoryEntry (
  ledgerSeq: Uint32, 
  txSet: TransactionSet, 
  ext: TransactionHistoryEntry.Ext
) {
  def encode(stream: XdrDataOutputStream): Unit = {
    ledgerSeq.encode(stream)
    txSet.encode(stream)
    ext.encode(stream)
  }
}

object TransactionHistoryEntry {
  def decode(stream: XdrDataInputStream): TransactionHistoryEntry = TransactionHistoryEntry(
    Uint32.decode(stream),
    TransactionSet.decode(stream),
    Ext.decode(stream)
  )

  sealed trait Ext {
    def encode(stream: XdrDataOutputStream): Unit
  }

  object Ext {
    def decode(stream: XdrDataInputStream): Ext = stream.readInt match {
      case 0 => R_0
      case d => throw new IllegalArgumentException(s"Int value $d is invalid")
    }

    case object R_0 extends Ext {
      def encode(stream: XdrDataOutputStream): Unit = {
        stream.writeInt(0)
      }
    }
  }
}
