// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  enum TrustLineFlags
//  {
//      // issuer has authorized account to perform transactions with its credit
//      AUTHORIZED_FLAG = 1
//  };

//  ===========================================================================

sealed class TrustLineFlags (val i: Int) {
  def encode(stream: XdrDataOutputStream) = stream.writeInt(i)
}

object TrustLineFlags {
  def decode(stream: XdrDataInputStream): TrustLineFlags = stream.readInt() match {
    case 1 => AUTHORIZED_FLAG
    case i => throw new IllegalArgumentException(s"TrustLineFlags value $i is invalid")
  }

  case object AUTHORIZED_FLAG extends TrustLineFlags(1)
}
