// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef opaque uint256[32];

//  ===========================================================================

case class Uint256 (self: Array[Byte]) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.write(self, 0, self.length)
  }
}
object Uint256 {
  def decode(stream: XdrDataInputStream): Uint256 = Uint256(stream.readBytes(32))
}
