// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef unsigned int uint32;

//  ===========================================================================

case class Uint32 (self: Int) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeInt(self)
  }
}
object Uint32 {
  def decode(stream: XdrDataInputStream): Uint32 = Uint32(stream.readInt)
}
