// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef unsigned hyper uint64;

//  ===========================================================================

case class Uint64 (self: Long) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeLong(self)
  }
}
object Uint64 {
  def decode(stream: XdrDataInputStream): Uint64 = Uint64(stream.readLong)
}
