// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package stellar.sdk.xdr

import stellar.sdk.xdr._

// === xdr source ============================================================

//  typedef opaque UpgradeType<128>;

//  ===========================================================================

case class UpgradeType (self: Array[Byte]) {
  def encode(stream: XdrDataOutputStream): Unit = {
    stream.writeInt(self.length)
    stream.write(self, 0, self.length)
  }
}
object UpgradeType {
  def decode(stream: XdrDataInputStream): UpgradeType = UpgradeType(stream.readBytes(stream.readInt))
}
